name: buildDockerImageARM

on:
  push:
    branches: [ "main" ]

  # pull_request:
  #   branches:
  #     - "master"

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
        - name: Check out the repo
          uses: actions/checkout@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push Docker image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: asslam1991/backend:1.1.${{ github.run_number }}
